@startuml
skinparam linetype polyline

class Artist {
 - artistName: String
 - firstName: String
 - lastName: String
 - monthlyListeners: int
}

class Album {
 - name: String
 - artist: Artist
 - genre: String
 - tracklist: List<Track>
}

class Track {
 - title: String
 - trackLength: LocalDate
 - artist: Artist
}

class Tour {
    - title: String
    - mainArtist: Artist
    - preAct: Artist
    - tourStops: List<Concert>
}

class Concert {
    - locationName: String
    - performingArtists: List<Artist>
    - date: LocalDate
    - adress: String
    - capacity: int
}


Artist "1*" -right--> "1*" Album: has >
Artist "1" <-left-- "1*" Track: has (single release) >
Artist "1" <--- "1*" Tour: performs >
Artist "1*" <--- "1*" Concert: performs >
Album "*" <--- "1" Track: is made of >
Tour "1" <-right-- "*" Concert: has >

@enduml
