@startuml

left to right direction

actor optiker as o

package "optiker verwaltung" {
    usecase "Kunden anlegen" as uc1
    usecase "Lagerbestand verwalten" as uc2
    usecase "Bestellungen absetzen" as uc3
}


o --> uc1
o --> uc2
o --> uc3



@enduml