@startuml

left to right direction

actor "Label Manager" as lm

package "Plattenlabel" {
    usecase "Neuen Artist anlegen" as uc1
    usecase "Neuveröffentlichungen bei Artists hinzufügen" as uc2
    usecase "Albumrelease hinzufügen" as uc21
    usecase "Singlerelease hinzufügen" as uc22
    usecase "Tour anlegen" as uc3
    usecase "Konzerte anlegen" as uc4
}


lm --> uc1
lm --> uc2
uc2 --> uc21
uc2 --> uc22
lm --> uc3
lm --> uc4



@enduml
